version: '3.8'

services:
  codecarbon-runner:
    build: .
    volumes:
      - ./results:/app/results
    environment:
      - CODECARBON_OUTPUT_DIR=/app/results

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./results:/app/results
      - ./backend:/app
    depends_on:
      - codecarbon-runner
    command: npm start

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start