version: '3.8'

services:
  codecarbon-runner:
    build: .
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    environment:
      - CODECARBON_OUTPUT_DIR=/app/results

  node-codecarbon:
    build: ./node-codecarbon
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    environment:
      - CODECARBON_OUTPUT_DIR=/app/results

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./results:/app/results
      - ./uploads:/app/uploads
      - ./backend:/app
      - ./logs:/app/logs
    depends_on:
      - codecarbon-runner
      - node-codecarbon
    command: npm start

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend